### DISCUSSION TITLE
Is there a way to use OpenStreetMap with the nice react-native-maps?

### DISCUSSION THREAD

**Discussion by ecosensors** [react-native-maps/react-native-maps#5245] [Feature requests]
I have built a Smartphone App with Cordova and I used Leaflet with OpenStreetMap to display the position of stations. I also added the feature markerClusterGroup.

Now, I rebuild my App with React Native and I am looking to keep my features. The best way would be to use Leaflet but I have not found a suitable solution.

I found React-native-map which looks very nice. Apparently, it works with Google map or Apple map which cost. Is there a way to use OpenStreetMap instead of Google and Apple Map? If yes, how?

Many thanks and have a good evening

**Comment by salah-ghanim** [comment]
@ecosensors we hop one day to have openstreetmap included, but no effort is planned yet.

**Comment by JaoSchmidt** [comment]
Also interested in this but

@salah-ghanim isn't it possible with Custom Tile Overlay? There is even an example using openstreetmap on README.md

**Reply by LukasB-DEV** [reply]
For ios it is possible to use the openstreetmap tile server. Android is blocked because of expensive loads in the past. Possible solution is to change the headers.

**Reply by JaoSchmidt** [reply]
Hello. I stopped using react-native-maps because it required me to use Google Maps API key, not using it would crash react-native.

I'm since using MapLibre, which solve that issue, however it still have the blocked problem you mentioned.

To solve this you can try to download the .pmtiles directly and host your own "openstreetmap" alternetive, like [tileserver-gl](https://github.com/maptiler/tileserver-gl)

Something like this:
```yml
tileserver:
    container_name: tileserver
    image: maptiler/tileserver-gl
    volumes:
      - "./tiles:/data"
      - "./tiles/config.json:/data/config.json"
    ports:
      - "8080:8080"
    command: ["--verbose"]
```
> In my case it was easier because I just needed a small area. If need the whole world then you will need 40Gb of space afaik
